name: On Release Published

on:
  release:
    types: [published]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Do something on release published
        run: echo "The release has been published!"
