name: Ubuntu build
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch from GitHub
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build Maven Project
        run: mvn -B package --file pom.xml

      - name: Set up a cache for Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build Ubuntu package
        run: |
          cd Halcyon
          mvn package jpackage:jpackage@ubuntu

      - name: '📦 Upload Package'
        run: |
          gh release upload ${{github.event.release.tag_name}} Halcyon/target/Halcyon*.jar
          gh release upload ${{github.event.release.tag_name}} /home/runner/work/Halcyon/Halcyon/Halcyon/dist/halcyon_1.0.0_amd64.deb
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash

      - name: List directory
        run: |
          cd Halcyon
          pwd
          ls -laF
          cd Halcyon
          pwd
          ls -laF
